title: CSE study
description: > # this means to ignore newlines until "baseurl:"
  강의 내용 정리 및 개발 공부하는 그런 Blog<br>
baseurl: "/csestudy" # the subpath of your site, e.g. /blog
url: "https://silent-han.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'J.H Han'
  last_name: 'Silent han'
  cv: '//github.com/silent-han'
  avatar: '/images/avatar.png'
  github_username:  silent-han  
  email: supercsehan@gmail.com
  vk_id: id201664979
  telegram_name: vikapitoshka 
  logo: '/images/github.svg'

# Build settings
markdown: kramdown

permalink: /csestudy/:categories/:year/:title.html


